modules/proxmox-ve/cluster.nix, modules/proxmox-ve/container.nix, modules/proxmox-ve/firewall.nix, modules/proxmox-ve/ha-manager.nix, modules/proxmox-ve/manager.nix
This fixes the bug introduced by https://github.com/SaumonNet/proxmox-nixos/pull/25.
=> Fix systemd units creation only when proxmox-ve is enabled

flake.lock, flake.nix, pkgs/default.nix, pkgs/pve-qemu/default.nix
Reverts SaumonNet/proxmox-nixos#32
We will not support overriding nixpkgs on the long run, so this code is not necessary anymore. 
This PR broke our automatic updates (see https://proxmox-nixos-update-logs.saumon.network/datadumper/2024-07-11.log)
=> Revert "fix: building on unstable using stable qemu"

README.md, flake.lock, flake.nix, tasks/update.nix
I understand the motivation of https://github.com/SaumonNet/proxmox-nixos/pull/40, and I'm cool with that; I understand that using this module with another version of nixpkgs is unsupported. However, I want to make sure it at least won't break the incompatible systems setup by overriding `pkgs.lib` with `lib` from nixos release.
This may break this module when it is used on version of nixpkgs older than supported, because there might be some missing `lib` functions, but I think it is okay, as this module only supports specified NixOS version.
If it is used on nixpkgs version newer than the released, it MAY break this module if something is changed/removed in upstream `lib`, however there is no breaking changes in it, because it may break too much code. Also, in case if upstream has …
=> fix: do not override lib with overlay

pkgs/pve-common/0003-pci-id-path.patch, pkgs/pve-common/default.nix
Fix the path of `pci.ids` file, so PCIe device names can be properly shown while adding PCI devices.
=> pve-common: fix PCI device name display

flake.lock, flake.nix, modules/proxmox-ve/cluster.nix, modules/proxmox-ve/default.nix, modules/proxmox-ve/linstor.nix, modules/proxmox-ve/manager.nix, pkgs/default.nix, pkgs/linstor-api-py/default.nix, pkgs/linstor-client/default.nix, pkgs/linstor-proxmox/default.nix, pkgs/linstor-server/build.patch, pkgs/linstor-server/default.nix, pkgs/linstor-server/deps.json, pkgs/proxmox-ve/default.nix, pkgs/pve-ha-manager/default.nix, pkgs/pve-manager/default.nix, pkgs/pve-storage/default.nix, tasks/update.nix, tests/default.nix, tests/linstor.nix
This adds:
- the Linstor server
- the Linstor client
- the Linstor Proxmox plugin
- options to enable [Linstor](https://linbit.com/blog/linstor-setup-proxmox-ve-volumes/) on Proxmox
- a NixOS test to check that Linstor works correctly.
=> Add support for LINSTOR to Proxmox VE

modules/proxmox-ve/manager.nix
This change adds `pkgs.btrfs-progs` and `pkgs.zfs` to `PATH` for two following systemd services to fix #28, and fix #63:
* `pvedaemon.service`
* `pvestatd.service`
This will make showing and creating btrfs / zfs storages work properly.
---
Fixed by adding binaries to path instead of patching the original perl scripts because the latter does not seem maintainable.
For example: https://github.com/proxmox/pve-storage/blob/ec5395868f5f24c0dcddd3f7e572db337160706e/src/PVE/Storage.pm#L1415, the command is composed as array and passed to `open3()` function. It is not very maintainable for me to patch the scripts as it is hard to distinguish commands and non-commands for `zfs`.  
---
=> pve-manager: add btrfs and zfs tools to service env paths

pkgs/default.nix, pkgs/pve-edk2-firmware/default.nix, pkgs/pve-qemu-server/default.nix, tests/vm.nix
This is another attempt of fixing UEFI by adding edk2 firmware (kudos to #47), which fix #14, #29 and #46. Instead of using prebuilt binaries, this PR builds the OVMF firmware from source.
All supported firmware architectures are built:
* IA32
* X64
* AArch64
* Riscv64
Compiling has been tested on both `x86_64-linux` and `aarch64-linux` builders.
Added vm creation unit test to cover following 4 scenarios:
* SeaBIOS (Legacy)
* OVMF (Legacy)
* OVMF (UEFI)
* OVMF (UEFI + Secure Boot)
Tested to be working:
---
One trade-off was made in this PR: I used `dpkg-source` for applying patches from Proxmox instead of Nix's native `patches` definition (e.g. the way [pve-qemu](https://github.com/SaumonNet/proxmox-nixos/blob/53f9cd6ad81f1bf36b257470d82e77e0629578c8/pkgs/pve-qemu/default.nix#L19) apply …
=> pve-edk2-firmware: init

pkgs/pve-edk2-firmware/default.nix
Upstream subhook repo is gone. Repalced with tianocore fork.
Links:
https://github.com/tianocore/edk2/issues/6398
https://github.com/NixOS/nixpkgs/pull/353800
=> pve-edk2-firmware: fix upstream submodule broken

pkgs/pve-novnc/default.nix, pkgs/update.py
This PR attempts to make `pve-novnc` support the existing update script by:
- Using Proxmox's git source and clone the original novnc as submodule
- Specify `sourceRoot` to `./novnc` to make existing build scripts compatible
- Add a `--version-prefix` parameter to `update.py` so we can limit the major.minor version of update target version. This is done to make sure build commands in nixpkgs are compatible for automatically updated versions.
Welcome any discussions on this method of working-around auto updates. If this is an acceptable solution for similar packages that needs both `src` and `src_patches` (e.g. `pve-qemu`), I plan to invest some time in updating these packages using the same pattern of this PR.
Tested by manually setting it to an older commit, then:
```bash
nix-shell …
```
=> pve-novnc: support update script

modules/proxmox-ve/manager.nix
I enabled PVE spiceproxy and tested it out with Display>Graphics Card: **SPICE (qxl)** & **VirtIO-GPU (virtio)**.   They both are working fine using virt-viewer when you click "Console: SPICE" in the web UI. 
On my system, I wasn't able to use VirGL GPU (virtio-gl). It can't seem to find the libraries (which is a different issue). I might be missing something, or paths are incorrect. More info on that [here](https://github.com/roperscrossroads/nixos-config/tree/main).
=> feat: add PVE spiceproxy

pkgs/pve-storage/default.nix
Without this dep, I get an error migrating a VM to my NixOS-based host:
```
2025-01-01 15:26:48 starting migration of VM 110 to node 'apollo' (10.0.2.11)
2025-01-01 15:26:48 found local disk 'local-zfs:vm-110-disk-0' (attached)
2025-01-01 15:26:48 found generated disk 'local-zfs:vm-110-disk-2' (in current VM config)
2025-01-01 15:26:48 copying local disk images
2025-01-01 15:26:49 full send of rpool/data/vm-110-disk-2@__migration__ estimated size is 45.0K
2025-01-01 15:26:49 total estimated size is 45.0K
2025-01-01 15:26:49 TIME        SENT   SNAPSHOT rpool/data/vm-110-disk-2@__migration__
2025-01-01 15:26:49 Can't locate XML/LibXML.pm in @INC (you may need to install the XML::LibXML module) (@INC entries checked: /nix/store/dvhhasabjbj305mj0czljrm235k38yvx-pve-storage-8.3.2/lib/perl5/site …
```
=> pve-storage: add XML::LibXML dep

modules/proxmox-ve/default.nix, modules/proxmox-ve/manager.nix, pkgs/cstream/default.nix, pkgs/default.nix, pkgs/pve-manager/default.nix, pkgs/pve-storage/default.nix
This is built on the work done in #45, plus:
- Fixes merge conflicts
- Removes some unneeded phases from the new cstream derivation
- Removes the `qmeventd` changes that aren't needed anymore
- Changes the plugin search path replacement to look under `/run/current-system/sw/lib`, so it will be able to find the plugins for both VMs and LXC containers
- Add `lxc` to the path for vzdump, since it will now check the path for LXC tools since the LXC plugin is getting loaded
- Add `zfs` and `btrfs-progs` to the `pvescheduler` service path, similar to other `pve-manager` services. I found my scheduled jobs didn't work even though the ones triggered manually did, and it seems like this is why.
=> Get backups working

modules/proxmox-ve/default.nix
The `SendEnv` setting here is assuming there isn't some other `Host` filters in `programs.ssh.extraConfig` that will appear before it, but that wasn't the case on my systems, as I have some host-specific configuration included. Adding `Host *` before `SendEnv` will ensure that no matter where it appears, it will still apply to all hosts.
Without this, the VNC proxy to other nodes in the cluster was failing because it wasn't sending the ticket along in the `LC_PVE_TICKET` env var.
=> ssh: add explicit host filter before SendEnv

pkgs/pve-edk2-firmware/default.nix
- Bumped `pve-edk2-firmware` to 4.2025.02-1
- Reverted changes in #79 because the issue has been fixed upstream. Kudos to @5aaee9 for the mitigation.
- Some readability improvements and added myself as maintainer for this package.
/cc maintainers @camillemndn @JulienMalka
=> pve-edk2-firmware: 4.2023.08-4 -> 4.2025.02-2

pkgs/pve-edk2-firmware/default.nix
Fix #134
Proxmox's edk2 mirror is no longer accessible (403 Forbidden): https://git.proxmox.com/?p=mirror_edk2.git , causing building pve-edk2-firmware to fail.
This PR switches the edk2 submodule to follow official edk2 repo, and bumped to the latest pve-edk2-firmware version.
=> pve-edk2-firmware: switch to official edk2 repo as upstream

modules/proxmox-ve/manager.nix, pkgs/pve-qemu-server/default.nix
`pvedaemon` call `swtpm_setup` to setup TPM support for vm. 
This patch add swtpm support and Windows 11 vm is require TPM.
=> Add TPM support

pkgs/proxmox-acme/default.nix, pkgs/pve-manager/default.nix
Fixes an issue mentioned on [NixOS discourse](https://discourse.nixos.org/t/announcing-proxmox-nixos/47579/14), where adding ACME account is failing with following error message:
```
TASK ERROR: Registration failed: Can't locate object method "bless_pointer" via package "Crypt::OpenSSL::Bignum" at blib/lib/Crypt/OpenSSL/RSA.pm (autosplit into blib/lib/auto/Crypt/OpenSSL/RSA/get_key_parameters.al) line 330. 
```
Following changes are made in this PR:
* [pve-manager] added missing perl dependency [CryptOpenSSLBignum](https://metacpan.org/dist/Crypt-OpenSSL-Bignum).
* [pve-acme] removed `--reset-env` when invoking `setpriv` so basic coreutils binaries could be discovered.
* [pve-acme] patched hardcoded paths for bash and curl.
Tested locally:
=> pve-manager: fix ordering acme certificate

pkgs/pve-qemu-server/default.nix
This PR patches the VirGL library detection logic in pve-qemu-server [Line 1835 of QemuServer.pm](https://git.proxmox.com/?p=qemu-server.git;a=blob;f=PVE/QemuServer.pm;h=82e7d6a6b0dc1e0ef9bad734901f0fe27e4da461;hb=54aa98cea5071b5cd325cfaeb21b7aaa4af9bb4d#l1835) to make VirGL virtualized graphics work.
Tested locally. Before this PR:
After this PR:
=> pve-qemu-server: fix libEGL/libGL detection to make VirGL work

pkgs/default.nix, pkgs/pve-http-server/default.nix, pkgs/sencha-touch/default.nix
This PR adds [sencha-touch](https://git.proxmox.com/?p=sencha-touch.git;a=summary) package to make Proxmox Web UI work when accessed from mobile devices. It is a dependency of `pve-http-server`.
Before this change:
After this change:
=> sencha-touch: init to fix pve mobile web ui not rendering

pkgs/proxmox-backup-qemu/default.nix
leaveDotGit was hurting hash stability, and is not necessary anymore
Better version of #152
=> proxmox-backup-qemu: remove leaveDotGit

pkgs/default.nix, pkgs/proxmox-i18n/default.nix, pkgs/pve-access-control/default.nix, pkgs/pve-common/0002-mknod-mknodat.patch, pkgs/pve-common/default.nix, pkgs/pve-guest-common/default.nix, pkgs/pve-manager/default.nix
This PR aims to upgrade pve-manager and related core packages one step at a time, since many iterations have happened in the past few months.
* proxmox-i18n: init at 3.2.4
* pve-manager: 8.2.4 -> 8.3.5
* pve-common: 8.2.1 -> 8.3.1
* pve-guest-common: 5.1.6 -> 5.1.7
* pve-access-control: 8.2.0 -> 8.2.2
=> Upgrade pve-manager and related core packages to versions around Jan. 2025

README.md, modules/proxmox-ve/bridges.nix, modules/proxmox-ve/default.nix
Add an option to declaratively set the list of bridges visible in Proxmox web interface, so users do not have to manually add the bridge on web interface.
This also helps if `/etc/network/interfaces` is not persisted across reboots, such as in an impermanence situation.
=> Add option to declaratively configure visible bridges

pkgs/nixmoxer/main.py
The methods vmid_exists and vm_name_exists crash with the error message `ValueError: not enough values to unpack (expected 3, got 0)` when the cluster contains no VMs.
This is because `tuple(zip())` (which is essentially what happens when there are no VMs) will return an empty tuple which cannot be unpacked. 
I added an extra check to both functions in order to prevent such crashes.
=> Fixed nixmoxer crash when there are no VMs on the cluster

pkgs/perlmod/Cargo.lock, pkgs/perlmod/default.nix, pkgs/pve-rs/Cargo.lock, pkgs/pve-rs/default.nix, pkgs/pve-rs/sources.nix
Fixes #167 
This PR bumps following two packages:
* pve-rs: 0.9.1 -> 0.9.4
* perlmod: 0.2.0-3 -> 0.2.1-1
Diff: https://github.com/proxmox/proxmox-perl-rs/compare/82bfbbf6c64b3749e3e982d933b9156e638386b2..22a6b226309923ddf6ca1982e813f5a273e0d427
Notes:
* pve-rs 0.9.4 is an official version that can be found under http://download.proxmox.com/debian/pve/dists/bookworm/pve-no-subscription/binary-amd64/
* perlmod is bumped accordingly to `pve-rs/debian/control` inside above diff.
* OIDC tested to be working:
=> pve-rs: 0.9.1 -> 0.9.4
